version: "3.8"

services:
  sqube:
    container_name: sonarqube
    image: sonarqube:latest
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    ports:
      - "5678:9000"
    networks:
      sqube_network:
        ipv4_address: 10.10.10.10
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  sdatabase:
    container_name: sonar_database
    image: postgres
    networks:
      sqube_network:
        ipv4_address: 10.10.10.11
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sqube_network:
    driver: bridge
    name: sqube_network
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/16

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
